import { Video } from './types';

export const TRANSLATIONS = {
  es: {
    home: "Inicio",
    movies: "Películas",
    series: "Series",
    novelas: "Novelas",
    sports: "Deportes",
    kids: "Niños",
    dashboard: "Panel Administrador",
    addMovie: "Subir Contenido",
    searchPlaceholder: "Buscar películas, series y más...",
    heroTagline: "¡MÁS DE 20,000 HORAS DE ENTRETENIMIENTO TOTALMENTE GRATIS!",
    heroDescription: "Disfruta de las mejores películas y series en español e inglés. Elige tu idioma y empieza a transmitir en alta definición sin suscripciones.",
    playNow: "Ver Ahora",
    myList: "Mi Lista",
    addedToList: "En Mi Lista",
    uploadSuccess: "¡Contenido subido exitosamente con perfil adaptativo!",
    uploadTitle: "Agregar Nueva Película o Serie",
    uploadSubtitle: "Completa el formulario para publicar un video en la plataforma. Los perfiles de bitrate adaptativo se crearán automáticamente. También puedes arrastrar archivos MP4 locales.",
    titleEs: "Título (Español)",
    titleEn: "Título (Inglés)",
    descEs: "Descripción (Español)",
    descEn: "Descripción (Inglés)",
    genreEs: "Género (Español)",
    genreEn: "Género (Inglés)",
    category: "Categoría",
    year: "Año",
    rating: "Clasificación",
    duration: "Duración",
    cast: "Reparto (separado por comas)",
    posterUrl: "URL de Imagen Poster",
    posterUrlDesc: "Usa un enlace o se generará un diseño gradiente elegante.",
    videoUrls: "Fuentes de Video (Bitrate Adaptativo)",
    video1080p: "Video URL (1080p - Alta Calidad)",
    video720p: "Video URL (720p - Media Calidad)",
    video480p: "Video URL (480p - Baja Calidad)",
    dragAndDropVideo: "Arrastra y suelta tu archivo de video MP4 aquí, o haz clic para seleccionarlo",
    customVideoFile: "Archivo de video seleccionado:",
    orUseWebUrls: "O proporciona enlaces Web MP4 arriba",
    subtitlesLabel: "Subtítulos (Formato VTT - Opcional)",
    subtitlesEs: "Subtítulos en Español (VTT Text)",
    subtitlesEn: "Subtítulos en Inglés (VTT Text)",
    submit: "Publicar Contenido",
    allCategories: "Todas las categorías",
    trending: "En Tendencia esta Semana",
    popularMovies: "Películas Más Vistas",
    exclusiveSeries: "Series Exclusivas",
    kidsCorner: "El Rincón de los Niños",
    newReleases: "Recién Agregados",
    customUploads: "Tus Videos Subidos",
    noCustomUploads: "Aún no has subido contenido. Usa el 'Panel Administrador' para subir tus primeras películas.",
    noResults: "No se encontraron resultados para tu búsqueda.",
    details: "Detalles",
    castLabel: "Elenco",
    genreLabel: "Género",
    playerSettings: "Ajustes",
    playerSpeed: "Velocidad de reproducción",
    playerQuality: "Calidad de video",
    playerSubtitles: "Subtítulos",
    playerNormal: "Normal",
    playerAuto: "Automático",
    playerOff: "Desactivado",
    theaterMode: "Modo Teatro",
    exitTheaterMode: "Modo Normal",
    pipMode: "Imagen en Imagen (PiP)",
    languageLabel: "Idioma",
    footerDisclaimer: "© 2026 Canela TV Clone & JWPlayer. Todos los derechos reservados. Desarrollado con tecnología de reproducción adaptativa HTML5 y rendimiento fluído.",
    footerLanguages: "Plataforma disponible en Español e Inglés con subtítulos adaptativos y cambio instantáneo.",
    vttSampleText: "Formato VTT: Puedes ingresar texto con marcas de tiempo (por ejemplo, '00:00:01.000 --> 00:00:05.000\\n¡Hola! Bienvenidos' ).",
    backToHome: "Volver al Inicio",
    ratingLabel: "Clasificación",
    yearLabel: "Año de Lanzamiento",
    durationLabel: "Duración",
  },
  en: {
    home: "Home",
    movies: "Movies",
    series: "Series",
    novelas: "Soap Operas",
    sports: "Sports",
    kids: "Kids",
    dashboard: "Admin Dashboard",
    addMovie: "Upload Content",
    searchPlaceholder: "Search movies, series, and more...",
    heroTagline: "OVER 20,000 HOURS OF TOTAL ENTERTAINMENT ABSOLUTELY FREE!",
    heroDescription: "Enjoy the best movies and series in English and Spanish. Choose your language and start streaming in High-Definition without any subscriptions.",
    playNow: "Play Now",
    myList: "My List",
    addedToList: "In My List",
    uploadSuccess: "Content successfully uploaded with adaptive profile!",
    uploadTitle: "Add New Movie or Series",
    uploadSubtitle: "Complete the form to publish a video on the platform. Adaptive bitrate profiles will be simulated/set up automatically. You can also drag and drop local MP4 files.",
    titleEs: "Title (Spanish)",
    titleEn: "Title (English)",
    descEs: "Description (Spanish)",
    descEn: "Description (English)",
    genreEs: "Genre (Spanish)",
    genreEn: "Genre (English)",
    category: "Category",
    year: "Year",
    rating: "Rating",
    duration: "Duration",
    cast: "Cast (separated by commas)",
    posterUrl: "Poster Image URL",
    posterUrlDesc: "Provide an image link, or an elegant gradient design will be generated.",
    videoUrls: "Video Sources (Adaptive Bitrate)",
    video1080p: "Video URL (1080p - High Quality)",
    video720p: "Video URL (720p - Medium Quality)",
    video480p: "Video URL (480p - Low Quality)",
    dragAndDropVideo: "Drag & drop your MP4 video file here, or click to browse",
    customVideoFile: "Selected video file:",
    orUseWebUrls: "Or provide web MP4 links above",
    subtitlesLabel: "Subtitles (VTT Format - Optional)",
    subtitlesEs: "Spanish Subtitles (VTT Text)",
    subtitlesEn: "English Subtitles (VTT Text)",
    submit: "Publish Content",
    allCategories: "All categories",
    trending: "Trending This Week",
    popularMovies: "Most Watched Movies",
    exclusiveSeries: "Exclusive Series",
    kidsCorner: "Kids Corner",
    newReleases: "Newly Added",
    customUploads: "Your Uploaded Videos",
    noCustomUploads: "You haven't uploaded any content yet. Use the 'Admin Dashboard' to upload your first movies.",
    noResults: "No results matched your search.",
    details: "Details",
    castLabel: "Cast",
    genreLabel: "Genre",
    playerSettings: "Settings",
    playerSpeed: "Playback speed",
    playerQuality: "Video quality",
    playerSubtitles: "Subtitles",
    playerNormal: "Normal",
    playerAuto: "Auto",
    playerOff: "Off",
    theaterMode: "Theater Mode",
    exitTheaterMode: "Normal Mode",
    pipMode: "Picture in Picture (PiP)",
    languageLabel: "Language",
    footerDisclaimer: "© 2026 Canela TV Clone & JWPlayer. All rights reserved. Built with advanced HTML5 adaptive playback technology for frictionless streaming.",
    footerLanguages: "Platform available in both Spanish and English with adaptive captioning and seamless switching.",
    vttSampleText: "VTT Format: Input text labeled with timestamps (e.g., '00:00:01.000 --> 00:00:05.000\\nHello! Welcome').",
    backToHome: "Back to Home",
    ratingLabel: "Rating",
    yearLabel: "Release Year",
    durationLabel: "Duration",
  }
};

export const DEFAULT_VIDEOS: Video[] = [
  {
    id: "v-ama-tu-projimo",
    title_es: "Ama a Tu Prójimo",
    title_en: "Love Thy Neighbor",
    description_es: "Una entrañable comedia y drama de la Época de Oro del cine mexicano, donde se narran con humor y gran sensibilidad los enredos diarios en una clínica de beneficencia.",
    description_en: "A tender comedy and drama from the Golden Era of Mexican Cinema, recounting with humor and sensitivity the daily entanglements in a welfare clinic.",
    category: "movies",
    genre_es: "Comedy, Drama, Classic",
    genre_en: "Comedy, Drama, Classic",
    duration: "1h 48m",
    poster_url: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=600",
    backdrop_url: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=1600",
    rating: "PG",
    year: "1958",
    cast: ["Mario Moreno Cantinflas", "Arturo de Córdova", "Marga López", "Kitty de Hoyos"],
    streams: [
      { label: "Auto", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" },
      { label: "1080p", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" },
      { label: "720p", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" }
    ]
  },
  {
    id: "v-ruptura",
    title_es: "La Ruptura de la Fe",
    title_en: "The Broken Faith",
    description_es: "Julian Gil explora la ruptura entre la selección y sus fans.",
    description_en: "Julian Gil explores the rift between the national team and its fans.",
    category: "sports",
    genre_es: "Sports, Soccer",
    genre_en: "Sports, Soccer",
    duration: "45min",
    poster_url: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?q=80&w=600",
    backdrop_url: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=1600",
    rating: "TV-PG",
    year: "2026",
    cast: ["Julian Gil", "Soccer Legends", "Coaches & Analysts"],
    streams: [
      { label: "Auto", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" },
      { label: "1080p", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" },
      { label: "720p", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" }
    ],
    episodes: [
      {
        id: "ruptura-e1",
        episodeNumber: 1,
        seasonNumber: 1,
        title_es: "El Quinto Partido",
        title_en: "The Fifth Match",
        duration: "45min",
        release_date: "2026-05-01",
        poster_url: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600",
        video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4"
      },
      {
        id: "ruptura-e2",
        episodeNumber: 2,
        seasonNumber: 1,
        title_es: "Presión en la Cancha",
        title_en: "Pitch Pressure",
        duration: "45min",
        release_date: "2026-05-08",
        poster_url: "https://images.unsplash.com/photo-1518063319789-7217e6706b04?q=80&w=600",
        video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
      }
    ]
  },
  {
    id: "v-pinamadura",
    title_es: "Piña Madura",
    title_en: "Piña Madura",
    description_es: "Una bailarina se entrega a un perverso y adinerado hombre para salvar la vida de su verdadero amor.",
    description_en: "Una bailarina se entrega a un perverso y adinerado hombre para salvar la vida de su verdadero amor.",
    category: "movies",
    genre_es: "Classic, Drama, Musical",
    genre_en: "Classic, Drama, Musical",
    duration: "1h 35m",
    poster_url: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?q=80&w=600",
    backdrop_url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?q=80&w=1600",
    rating: "TV-PG",
    year: "1950",
    cast: ["María Antonieta Pons", "Armando Calvo", "José Piñeiro", "Queta Lavat"],
    director: "Miguel Zacarías",
    country: "Mexico",
    streams: [
      { label: "Auto", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4" }
    ]
  },
  {
    id: "v-venganzasalvaje",
    title_es: "Venganza Salvaje",
    title_en: "Savage Vengeance",
    description_es: "Dos hermanos buscan justicia en una ciudad sin ley tras el ataque a su rancho familiar. Acción y drama al límite.",
    description_en: "Two brothers seek justice in a lawless city after their family ranch is attacked. Extreme action and drama.",
    category: "movies",
    genre_es: "Acción, Drama, Thriller",
    genre_en: "Action, Drama, Thriller",
    duration: "1h 48m",
    poster_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=600",
    rating: "TV-MA",
    year: "2023",
    cast: ["Salvador Zerboni", "Ivonne Montero", "Alejandro Tommasi"],
    streams: [
      { label: "Auto", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" }
    ]
  },
  {
    id: "v-undivorcio",
    title_es: "Un Divorcio",
    title_en: "A Divorce",
    description_es: "Un drama clásico que aborda las tensiones religiosas y morales de un matrimonio en crisis a mediados del siglo XX.",
    description_en: "A classic drama addressing the moral and religious tensions of a marriage in crisis in the mid-20th century.",
    category: "novelas",
    genre_es: "Clásicos, Drama",
    genre_en: "Classics, Drama",
    duration: "1h 40m",
    poster_url: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=600",
    rating: "PG",
    year: "1953",
    cast: ["Arturo de Córdova", "Marga López", "Elda Peralta"],
    streams: [
      { label: "Auto", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4" }
    ]
  },
  {
    id: "v-glorias",
    title_es: "Glorias Mundialistas",
    title_en: "World Cup Glories",
    description_es: "Un recuento emocionante de las leyendas vivas, partidos épicos y los momentos más memorables de la historia de los mundiales.",
    description_en: "A thrilling count of the living legends, epic matches, and the most memorable moments in World Cup history.",
    category: "sports",
    genre_es: "Deportes, Documental",
    genre_en: "Sports, Documentary",
    duration: "55m",
    poster_url: "https://images.unsplash.com/photo-1518063319789-7217e6706b04?q=80&w=600",
    rating: "TV-G",
    year: "2022",
    cast: ["Soccer Experts", "World Cup Champions"],
    streams: [
      { label: "Auto", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" }
    ]
  },
  {
    id: "v-unamigo",
    title_es: "Un Amigo en Mente",
    title_en: "A Friend in Mind",
    description_es: "La tierna aventura de un niño y su adorable cachorro canino que descifran juntos los pequeños misterios cotidianos.",
    description_en: "The tender adventure of a boy and his adorable puppy who together decode the little everyday mysteries of life.",
    category: "kids",
    genre_es: "Familiar, Drama, Niños",
    genre_en: "Family, Drama, Kids",
    duration: "1h 32m",
    poster_url: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?q=80&w=600",
    rating: "G",
    year: "2021",
    cast: ["Leo Miller", "Max the Puppy"],
    streams: [
      { label: "Auto", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" }
    ]
  },
  {
    id: "v-pobrespero",
    title_es: "Pobres Pero Sinvergüenzas",
    title_en: "Poor But Shameless",
    description_es: "Dos amigos ingeniosos y sin blanca idean los planes más disparatados para salir adelante, desatando la risa en el vecindario.",
    description_en: "Two visual, penniless friends design-mind the most hilarious schemes to succeed in local towns.",
    category: "movies",
    genre_es: "Comedia, Clásicos",
    genre_en: "Comedy, Classics",
    duration: "1h 28m",
    poster_url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=600",
    rating: "TV-PG",
    year: "1983",
    cast: ["Manolín", "Shilinsky"],
    streams: [
      { label: "Auto", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4" }
    ]
  },
  {
    id: "v-desolado",
    title_es: "Desolado con Ed Stafford",
    title_en: "Marooned with Ed Stafford",
    description_es: "Ed Stafford es abandonado sin comida, agua ni herramientas en las zonas más agrestes de la Tierra para demostrar que puede sobrevivir por 10 días.",
    description_en: "Ed Stafford is left with absolute zero food, gear, or water in the most extreme ecosystems of Earth.",
    category: "series",
    genre_es: "Aventura, Reality, Deportes",
    genre_en: "Adventure, Reality, Sports",
    duration: "45m",
    poster_url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?q=80&w=600",
    rating: "TV-PG",
    year: "2016",
    cast: ["Ed Stafford"],
    streams: [
      { label: "Auto", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" }
    ]
  },
  {
    id: "v-designacion",
    title_es: "La Designación Ultra",
    title_en: "The Ultra Designation",
    description_es: "Un thriller tecnológico de alta tensión donde el destino de un país entero depende de la elección de un enigmático algoritmo.",
    description_en: "A high-tension techno-thriller where the destiny of a nation depends on a secretive system algorithm.",
    category: "movies",
    genre_es: "Ciencia Ficción, Acción",
    genre_en: "Sci-Fi, Action",
    duration: "1h 50m",
    poster_url: "https://images.unsplash.com/photo-1515263487990-61b07816b324?q=80&w=600",
    rating: "TV-14",
    year: "2025",
    cast: ["Cyber Officers", "Tech Leads"],
    streams: [
      { label: "Auto", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4" }
    ]
  },
  {
    id: "v-safir",
    title_es: "Safir",
    title_en: "Safir",
    description_es: "Una desgarradora historia de amor y venganza en Estambul entre una joven humilde y el heredero de un gran imperio industrial.",
    description_en: "A heartwrenching tale of romance, family feud, and secrets in majestic Cappadocia.",
    category: "series",
    genre_es: "Drama, Romance",
    genre_en: "Drama, Romance",
    duration: "1 Temporada",
    poster_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=600",
    rating: "TV-14",
    year: "2023",
    cast: ["İlhan Şen", "Özge Yağız", "Burak Berkay Akgül"],
    streams: [
      { label: "Auto", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" }
    ]
  },
  {
    id: "v-corazon",
    title_es: "Corazón Apasionado",
    title_en: "Passionate Heart",
    description_es: "Un romance ardiente que desafía los prejuicios de clases y enciende la pasión rural mexicana entre haciendas y secretos.",
    description_en: "An intense romantic drama challenging high social classes amidst ranches and family conspiracies.",
    category: "novelas",
    genre_es: "Romance, Drama",
    genre_en: "Romance, Drama",
    duration: "1 Temporada",
    poster_url: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?q=80&w=600",
    rating: "TV-14",
    year: "2012",
    cast: ["Marlene Favela", "Guy Ecker", "Lorena Meritano"],
    streams: [
      { label: "Auto", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4" }
    ]
  },
  {
    id: "v-mayday",
    title_es: "Mayday: Catástrofes Aéreas",
    title_en: "Mayday: Air Disasters",
    description_es: "Reconstrucción detallada y emocionante de los accidentes aéreos más impactantes e inexplicables de la historia moderna de la aviación.",
    description_en: "Detailed reconstructive visual logs of the most famous and shocking flight incidents in aviation history.",
    category: "series",
    genre_es: "Acción, Documental",
    genre_en: "Action, Documentary",
    duration: "23 Temporadas",
    poster_url: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=600",
    rating: "TV-PG",
    year: "2003",
    cast: ["Flight Safety Staff", "Crash Investigators"],
    streams: [
      { label: "Auto", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" }
    ]
  },
  {
    id: "v-hercai",
    title_es: "Hercai, Amor y Venganza",
    title_en: "Hercai, Love & Vengeance",
    description_es: "Miran quiere vengar la muerte de sus padres, pero su plan se complica cuando, en el proceso, se enamora de una persona que representa una parte clave del plan.",
    description_en: "Miran seeks to avenge the death of his parents, but his plan is complicated when, on the way, he falls in love with a person who represents a key part of his family vendetta.",
    category: "novelas",
    genre_es: "Novela, Drama, Romance",
    genre_en: "Soap Opera, Drama, Romance",
    duration: "1 Temporada",
    poster_url: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?q=80&w=600",
    backdrop_url: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?q=80&w=1600",
    rating: "TV-14",
    year: "2019",
    cast: ["Akin Akinozu", "Ebru Sahin", "Ayda Aksel", "Serhat Tutumluer", "Oya Unustasi"],
    streams: [
      { label: "1080p", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" },
      { label: "720p", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" },
      { label: "480p", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" }
    ],
    episodes: [
      {
        id: "hercai-e1",
        episodeNumber: 1,
        seasonNumber: 1,
        title_es: "La Nieta",
        title_en: "The Granddaughter",
        duration: "45min",
        release_date: "16 Mar, 2019",
        poster_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=400",
        video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4"
      },
      {
        id: "hercai-e2",
        episodeNumber: 2,
        seasonNumber: 1,
        title_es: "La Elección de Miran",
        title_en: "Miran's Choice",
        duration: "45min",
        release_date: "16 Mar, 2019",
        poster_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=400",
        video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4"
      },
      {
        id: "hercai-e3",
        episodeNumber: 3,
        seasonNumber: 1,
        title_es: "Confianza",
        title_en: "Trust",
        duration: "42min",
        release_date: "16 Mar, 2019",
        poster_url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=400",
        video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
      }
    ]
  },
  {
    id: "v-esclava",
    title_es: "La Esclava Madre",
    title_en: "The Slave Mother",
    description_es: "Una superproducción dramática brasileña que se sumerge en las intensas y emocionantes luchas por la libertad e igualdad de clases coloniales.",
    description_en: "An epic colonial Brazilian drama portraying powerful efforts for freedom and survival.",
    category: "novelas",
    genre_es: "Drama, Histórica",
    genre_en: "Drama, History",
    duration: "1 Temporada",
    poster_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=600",
    rating: "TV-14",
    year: "2016",
    cast: ["Gabriela Moreyra", "Pedro Carvalho", "Fernando Pavão"],
    streams: [
      { label: "Auto", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" }
    ]
  },
  {
    id: "v-secretos",
    title_es: "Secretos de Villanas",
    title_en: "Secrets of Villains",
    description_es: "Las villanas más icónicas e implacables de las telenovelas se reúnen juntas de vacaciones en este reality show explosivo donde revelan rivalidades y oscuras verdades.",
    description_en: "The most legendary villain players of soap operas unite in a luxury vacation to share rivalries.",
    category: "series",
    genre_es: "Reality, Drama",
    genre_en: "Reality, Drama",
    duration: "2 Temporadas",
    poster_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600",
    rating: "TV-14",
    year: "2022",
    cast: ["Gaby Spanic", "Laura Zapata", "Cynthia Klitbo", "Sabine Moussier"],
    streams: [
      { label: "Auto", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" }
    ]
  },
  {
    id: "v-capo",
    title_es: "Capo: El Amo del Túnel",
    title_en: "Capo: Master of the Tunnel",
    description_es: "Inspirada en hechos reales, narra la espectacular y arriesgada fuga carcelaria del capo de la droga más poderoso de la era moderna a través de un túnel kilométrico.",
    description_en: "Inspired by real events, tracing the spectacular custom tunnel breakout of the world's kingpin.",
    category: "series",
    genre_es: "Acción, Suspenso",
    genre_en: "Action, Suspense",
    duration: "2 Temporadas",
    poster_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=600",
    rating: "TV-MA",
    year: "2016",
    cast: ["Irán Castillo", "José María Yazpik", "Mauricio Ochmann"],
    streams: [
      { label: "Auto", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4" }
    ]
  },
  {
    id: "v-sintetas",
    title_es: "Sin Tetas No Hay Paraíso",
    title_en: "Without Breasts There Is No Paradise",
    description_es: "La dramática historia de Catalina, una joven atraída por la red de dinero fácil de los capos del narcotráfico locales, enfrentando consecuencias extremas.",
    description_en: "Catalina is pulled into dangerous golden fields of easy currency, bearing absolute moral tolls.",
    category: "novelas",
    genre_es: "Drama, Clásicos",
    genre_en: "Drama, Classics",
    duration: "1 Temporada",
    poster_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=600",
    rating: "TV-MA",
    year: "2008",
    cast: ["María Adelaida Puerta", "Patricia Ércole", "Sandra Beltrán"],
    streams: [
      { label: "Auto", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4" }
    ]
  },
  {
    id: "v-promesa",
    title_es: "La Promesa",
    title_en: "The Promise",
    description_es: "Tres mujeres con pasados opuestos son engañadas por una mafia internacional, uniéndose en una valiente lucha colectiva por la supervivencia.",
    description_en: "Three people with distinct backgrounds unite to dismantle a complex ring to regain freedom.",
    category: "novelas",
    genre_es: "Drama, Romance",
    genre_en: "Drama, Romance",
    duration: "1 Temporada",
    poster_url: "https://images.unsplash.com/photo-1464746133101-a2c3f88e0dd9?q=80&w=600",
    rating: "TV-14",
    year: "2012",
    cast: ["Julieth Restrepo", "Aislinn Derbez", "Nicole Santamaría"],
    streams: [
      { label: "Auto", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" }
    ]
  },
  {
    id: "v-fazilet",
    title_es: "La Señora Fazilet y Sus Hijas",
    title_en: "La Señora Fazilet y Sus Hijas",
    description_es: "Una madre obsesionada con ascender socialmente empuja a sus hijas a un mundo de lujo y poder, donde el amor, la rivalidad y los secretos familiares lo cambian todo.",
    description_en: "A mother obsessed with social climbing pushes her daughters into a world of luxury and power, where love, rivalry, and family secrets change everything.",
    category: "novelas",
    genre_es: "Novela, Drama",
    genre_en: "Soap Opera, Drama",
    duration: "1 Temporada",
    poster_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=600",
    backdrop_url: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?q=80&w=1600",
    rating: "TV-14",
    year: "2017",
    cast: ["Nazan Kesal", "Deniz Baysal", "Caglar Ertugrul", "Mahir Günsiray", "Tolga Güleç", "Hazal Türesan"],
    director: "Gökçen Usta, Murat Saraçoğlu, Alptekin Bozkurt, Günay Günaydín",
    country: "Turkey",
    isFeatured: true,
    streams: [
      { label: "Auto", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" },
      { label: "1080p", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" }
    ],
    episodes: [
      {
        id: "fazilet-e1",
        episodeNumber: 1,
        seasonNumber: 1,
        title_es: "Escapar de la Pobreza",
        title_en: "Escape from Poverty",
        duration: "43min",
        release_date: "26 Mar, 2017",
        poster_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=400",
        video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4"
      },
      {
        id: "fazilet-e2",
        episodeNumber: 2,
        seasonNumber: 1,
        title_es: "Amor Secreto",
        title_en: "Secret Love",
        duration: "45min",
        release_date: "26 Mar, 2017",
        poster_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=400",
        video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4"
      },
      {
        id: "fazilet-e3",
        episodeNumber: 3,
        seasonNumber: 1,
        title_es: "La Familia Egemen",
        title_en: "The Egemen Family",
        duration: "47min",
        release_date: "26 Mar, 2017",
        poster_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400",
        video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
      },
      {
        id: "fazilet-e4",
        episodeNumber: 4,
        seasonNumber: 1,
        title_es: "Búsqueda de Riqueza",
        title_en: "Search for Wealth",
        duration: "43min",
        release_date: "26 Mar, 2017",
        poster_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400",
        video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4"
      },
      {
        id: "fazilet-e5",
        episodeNumber: 5,
        seasonNumber: 1,
        title_es: "Choque de Mundos",
        title_en: "Clash of Worlds",
        duration: "44min",
        release_date: "26 Mar, 2017",
        poster_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=400",
        video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4"
      }
    ]
  }
];
